# Generated by Django 4.1.3 on 2023-01-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enitity',
            new_name='Entity',
        ),
    ]
